In [11]:
import json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

ROOT_DIR = Path.cwd()
if not (ROOT_DIR / "data" / "dblp-1.csv").exists():
    ROOT_DIR = ROOT_DIR / "project"
DATA_DIR = ROOT_DIR / "data"

In [12]:
con = duckdb.connect(database=":memory:")

dblp_1_path = DATA_DIR / "dblp-1.csv"
dblp_2_path = DATA_DIR / "dblp-2.csv"
dblp_3_path = DATA_DIR / "dblp-3.csv"
dblp_4_path = DATA_DIR / "dblp-4.csv"

df = con.query(f"""
    SELECT * FROM read_csv_auto('{dblp_1_path}')
    UNION ALL
    SELECT * FROM read_csv_auto('{dblp_2_path}')
    UNION ALL
    SELECT * FROM read_csv_auto('{dblp_3_path}')
    UNION ALL
    SELECT * FROM read_csv_auto('{dblp_4_path}')
""")

df.show()

┌──────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬──────────┬────────────┬─────────┬─────────┬────────────────────────────────┬──────────┬─────────────┬───────────────┬─────────────────┬───────────────────┬───────────┐
│ column00 │                                                                   pauthor                                                                   │ peditor │                                                 ptitle                                                 │ pyear │ paddress │ ppublisher │ pseries │   pid   │              pkey              │ ptype_id │ pjournal_id │ pbooktitle_id │ pjournalfull_id │ pbooktitlefull_id │ partition │
│  int64   │                                                                   varchar                                                                   │ varchar │                                                varchar                                                 │ int64 │ varchar  │  varchar   │ varchar │  int64  │            varchar             │  int64   │    int64    │     int64     │      int64      │       int64       │   int64   │
├──────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼──────────┼────────────┼─────────┼─────────┼────────────────────────────────┼──────────┼─────────────┼───────────────┼─────────────────┼───────────────────┼───────────┤
│        4 │ Jorge Semião|Juan J. Rodríguez-Andina|Fabian Vargas|Marcelino Bicho Dos Santos|Isabel C. Teixeira|João Paulo Teixeira                       │ NULL    │ Improving the Tolerance of Pipeline Based Circuits to Power Supply or Temperature Variations.          │ -2007 │ NULL     │ NULL       │ NULL    │  180843 │ conf/dft/SemiaoRVSTT07         │        1 │           0 │             4 │               0 │                 4 │         1 │
│        7 │ Patrice Caire                                                                                                                               │ NULL    │ A Normative Multi-Agent Systems Approach to the Use of Conviviality for Digital Cities.                │ -2007 │ NULL     │ NULL       │ NULL    │  162991 │ conf/dagstuhl/Caire07          │        2 │           0 │             7 │               0 │                 7 │         1 │
│       10 │ Sundeep B|Andrew Thangaraj                                                                                                                  │ NULL    │ Self-Orthogonality of q-Ary Images of qm-Ary Codes and Quantum Code Construction.                      │  2007 │ NULL     │ NULL       │ NULL    │ 2261406 │ journals/tit/BT07              │        0 │           2 │             9 │               2 │                 9 │         1 │
│       18 │ Gerardo Pardo-Castellote                                                                                                                    │ NULL    │ OMG Data-Distribution Service: Architectural Overview.                                                 │ -2003 │ NULL     │ NULL       │ NULL    │  349720 │ conf/icdcsw/Pardo-Castellote03 │        1 │           0 │            11 │               0 │                11 │         1 │
│       19 │ Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-Soo Kim 0002                                                                                  │ NULL    │ Structural Consistency: Enabling XML Keyword Search to Eliminate Spurious Results Consistently         │  2009 │ NULL     │ NULL       │ NULL    │ 1922328 │ journals/corr/abs-0911-4329    │        3 │           5 │             5 │               5 │                 5 │         1 │
│       20 │ Bin Liu|David J. Hill|Kok Lay Teo                                                                                                           │ NULL    │ Input-to-state stability for a class of hybrid dynamical systems via hybrid time approach.             │ -2009 │ NULL     │ NULL       │ NULL    │  883711 │ conf/cdc/LiuHT09               │        1 │           0 │             5 │               0 │                 5 │         1 │
│       22 │ A fourth-order compact difference scheme on face centered cubic grids with multigrid method for solving 2D convection diffusion equation.   │ NULL    │ Haiwei Sun|Ning Kang|Jun Zhang|Eric S. Carlson                                                         │ -2003 │ NULL     │ NULL       │ NULL    │ 2324621 │ journals/mcs/SunKZC03          │        3 │           6 │             5 │               6 │                 5 │         1 │
│       28 │ Sang-Heon Lee|Nam-Sung Kim|Heau-Jo Kang|Soon-Gohn Kim                                                                                       │ NULL    │ Performance Improvement of Intelligent UWB-IR Communication System in Multipath Channel.               │ -2006 │ NULL     │ NULL       │ NULL    │  366780 │ conf/icic/LeeKKK06             │        0 │           0 │             0 │               0 │                 0 │         1 │
│       33 │ Eugene Pamba Capo-Chichi|Hervé Guyennet|Jean-Michel Friedt                                                                                  │ NULL    │ IEEE 802.15.4 Performance on a Hierarchical Hybrid Sensor Network Platform.                            │ -2009 │ NULL     │ NULL       │ NULL    │  794722 │ conf/icns/Capo-ChichiGF09      │        2 │           0 │            15 │               0 │                15 │         1 │
│       39 │ Feng Wang|Michael J. Hannafin                                                                                                               │ NULL    │ Scaffolding preservice teachers' WebQuest design: a qualitative study.                                 │ -2009 │ NULL     │ NULL       │ NULL    │ 2339884 │ journals/jche/WangH09          │        0 │          10 │             5 │              10 │                 5 │         1 │
│        · │               ·                                                                                                                             │  ·      │                                   ·                                                                    │   ·   │  ·       │  ·         │  ·      │    ·    │           ·                    │        · │           · │             · │               · │                 · │         · │
│        · │               ·                                                                                                                             │  ·      │                                   ·                                                                    │   ·   │  ·       │  ·         │  ·      │    ·    │           ·                    │        · │           · │             · │               · │                 · │         · │
│        · │               ·                                                                                                                             │  ·      │                                   ·                                                                    │   ·   │  ·       │  ·         │  ·      │    ·    │           ·                    │        · │           · │             · │               · │                 · │         · │
│     6090 │ Ravindra Patankar|Roger Xu|Hongda Chen|David Patterson                                                                                      │ NULL    │ Global search algorithm for automated maintenance planning and scheduling of parts requests.           │ -2009 │ NULL     │ NULL       │ NULL    │ 1903470 │ journals/cor/PatankarXCP09     │        2 │          66 │             5 │              66 │                 5 │         3 │
│     6091 │ One Knowledge Discovery Approach for Product Conceptual Design.                                                                             │ NULL    │ Zhen Peng|Bingru Yang|Wu Qu                                                                            │  2009 │ NULL     │ NULL       │ NULL    │  903087 │ conf/jcai/PengYQ09             │        2 │           0 │          1621 │               0 │              1621 │         3 │
│     6106 │ Julio Pacheco|M. Teresa Escrig                                                                                                              │ NULL    │ Coarse Qualitative Model of 3-D Orientation.                                                           │ -2006 │ NULL     │ NULL       │ NULL    │   98031 │ conf/ccia/PachecoE06           │        0 │           0 │           245 │               0 │               245 │         3 │
│     6107 │ Focal Activity in Simulated LQT2 Models at Rapid Ventricular Pacing: Analysis of Cardiac Electrical Activity Using Grid-Based Computation.  │ NULL    │ Chong Wang|Antje Krause|Chris D. Nugent|Werner Dubitzky                                                │  2005 │ NULL     │ NULL       │ NULL    │  515259 │ conf/ismda/WangKND05           │        1 │           0 │           459 │               0 │               459 │         3 │
│     6124 │ Expert Conciliation for Multi Modal Person Authentication Systems by Bayesian Statistics.                                                   │ NULL    │ Elizabeth Saers Bigün|Josef Bigün|Benoît Duc|Stefan Fischer 0005                                       │  1997 │ NULL     │ NULL       │ NULL    │   70927 │ conf/avbpa/BigunBDF97          │        1 │           0 │           501 │               0 │               501 │         3 │
│     6130 │ Carlos A. M. Del Carpio|Mohamed Ismael|Eiichiro Ichiishi|Michihisa Koyama|Momoji Kubo|Akira Miyamoto                                        │ NULL    │ An Evolving Automaton for RNA Secondary Structure Prediction.                                          │ -2006 │ NULL     │ NULL       │ NULL    │  463005 │ conf/ijcnn/CarpioIIKKM06       │        1 │           0 │            80 │               0 │                80 │         3 │
│     6131 │ Atau Tanaka                                                                                                                                 │ NULL    │ Mobile Music Making.                                                                                   │ -2004 │ NULL     │ NULL       │ NULL    │  603932 │ conf/nime/Tanaka04             │        1 │           0 │          1627 │               0 │              1627 │         3 │
│     6149 │ Ein Werkzeug zur Gewinnung semantischer Constraints aus natürlichsprachlichen Eingaben und Beispieldaten.                                   │ NULL    │ Meike Albrecht|Edith Buchholz|Antje Düsterhöft|Bernhard Thalheim                                       │ -1995 │ NULL     │ NULL       │ NULL    │   81979 │ conf/btw/AlbrechtBDT95         │        4 │           0 │          1038 │               0 │              1038 │         3 │
│     6151 │ Gilles Barthe|Lennart Beringer|Pierre Crégut|Benjamin Grégoire|Martin Hofmann|Peter Müller|Erik Poll|Germán Puebla|Ian Stark|Eric Vétillard │ NULL    │ MOBIUS: Mobility, Ubiquity, Security.                                                                  │  2006 │ NULL     │ NULL       │ NULL    │  736485 │ conf/tgc/BartheBCGHMPPSV06     │        1 │           0 │          1629 │               0 │              1629 │         3 │
│     6158 │ Jin Ha Lee                                                                                                                                  │ NULL    │ Analysis of user needs and information features in natural language queries seeking music information. │  2010 │ NULL     │ NULL       │ NULL    │ 2084814 │ journals/jasis/Lee10           │        3 │         355 │             0 │             355 │                 0 │         3 │
└──────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┴──────────┴────────────┴─────────┴─────────┴────────────────────────────────┴──────────┴─────────────┴───────────────┴─────────────────┴───────────────────┴───────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                  16 columns

### Using pandas for the json files

In [13]:
def load_lookup(path):
    with open(path) as f:
        raw = json.load(f)
    df_lu = pd.DataFrame(raw) 
    return dict(zip(df_lu["id"], df_lu["name"]))

In [14]:
ptype        = load_lookup(DATA_DIR / "ptype.json")
pjournal     = load_lookup(DATA_DIR / "pjournal.json")
pjournalfull = load_lookup(DATA_DIR / "pjournalfull.json")
pbooktitle   = load_lookup(DATA_DIR / "pbooktitle.json")
pbooktitlefull = load_lookup(DATA_DIR / "pbooktitlefull.json")

id_mappings = {
    "ptype_id":          ptype,
    "pjournal_id":       pjournal,
    "pbooktitle_id":     pbooktitle,
    "pjournalfull_id":   pjournalfull,
    "pbooktitlefull_id": pbooktitlefull,
}

for name, m in [("ptype", ptype), ("pjournal", pjournal),
                ("pjournalfull", pjournalfull), ("pbooktitle", pbooktitle),
                ("pbooktitlefull", pbooktitlefull)]:
    print(f"{name}: {len(m)} rows")

ptype: 9 rows
pjournal: 718 rows
pjournalfull: 90 rows
pbooktitle: 2720 rows
pbooktitlefull: 1084 rows

Transforming the dicts from the json files into duckdb tables in order to perform JOIN

In [15]:
ptype_df = pd.DataFrame(list(ptype.items()), columns=["id", "name"])
con.register("ptype_df", ptype_df)

pjournal_df = pd.DataFrame(list(pjournal.items()), columns=["id", "name"])
pjournalfull_df = pd.DataFrame(list(pjournalfull.items()), columns=["id", "name"])
con.register("pjournal_df", pjournal_df)
con.register("pjournalfull_df", pjournalfull_df)

pbooktitle_df = pd.DataFrame(list(pbooktitle.items()), columns=["id", "name"])
pbooktitlefull_df = pd.DataFrame(list(pbooktitlefull.items()), columns=["id", "name"])
con.register("pbooktitle_df", pbooktitle_df)
con.register("pbooktitlefull_df", pbooktitlefull_df)

In [16]:
pbooktitle_df

        id                                            name
0        0                                             nán
1        1                                     VLSI Design
2        2                            Prozeßrechnersysteme
3        3                                          PRICAI
4        4                                             DFT
...    ...                                             ...
2715  2715                        Symposium on Programming
2716  2716                                            TLDI
2717  2717  ECML Workshop on Learning Contex-Free Grammars
2718  2718                  Concurrency, Graphs and Models
2719  2719                                     CompSysTech

[2720 rows x 2 columns]

## Missing/NULL/NaN values

In [17]:
con.query("""
    SELECT COUNT(*) AS null_count
    FROM df
    WHERE pbooktitle_id = 0
""").show()

┌────────────┐
│ null_count │
│   int64    │
├────────────┤
│       1686 │
└────────────┘

## Dropping NULL Columns
- paddress
- ppublisher
- pseries
- peditor

In [18]:
con.query("SELECT COUNT(*) FROM df").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        17165 │
└──────────────┘

In [19]:
df_new = con.query("""
        SELECT 
            df.pauthor, 
            df.ptitle, 
            df.pyear, 
            df.pid, 
            df.pkey,
            df.ptype_id,
            df.pjournal_id,
            df.pjournalfull_id,
            df.pbooktitle_id,
            df.pbooktitlefull_id,
            ptype_df.name         AS ptype,
            pjournal_df.name      AS journal,
            pjournalfull_df.name  AS journalfull,
            pbooktitle_df.name    AS booktitle,
            pbooktitlefull_df.name AS booktitlefull
        FROM df 
        LEFT JOIN ptype_df
            ON df.ptype_id = ptype_df.id
        LEFT JOIN pjournal_df
            ON df.pjournal_id = pjournal_df.id
        LEFT JOIN pjournalfull_df
            ON df.pjournalfull_id = pjournalfull_df.id
        LEFT JOIN pbooktitle_df
            ON df.pbooktitle_id = pbooktitle_df.id
        LEFT JOIN pbooktitlefull_df
            ON df.pbooktitlefull_id = pbooktitlefull_df.id
    """)

In [20]:
con.query("SELECT COUNT(*) FROM df_new").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        17165 │
└──────────────┘

In [21]:
df_new.show()

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┬────────────────────────────────┬──────────┬─────────────┬─────────────────┬───────────────┬───────────────────┬───────────────┬─────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────┬────────────────────────────────────────────────────────┐
│                                                                  pauthor                                                                  │                                                    ptitle                                                     │ pyear │   pid   │              pkey              │ ptype_id │ pjournal_id │ pjournalfull_id │ pbooktitle_id │ pbooktitlefull_id │     ptype     │                 journal                 │                             journalfull                             │                     booktitle                     │                     booktitlefull                      │
│                                                                  varchar                                                                  │                                                    varchar                                                    │ int64 │  int64  │            varchar             │  int64   │    int64    │      int64      │     int64     │       int64       │    varchar    │                 varchar                 │                               varchar                               │                      varchar                      │                        varchar                         │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼─────────┼────────────────────────────────┼──────────┼─────────────┼─────────────────┼───────────────┼───────────────────┼───────────────┼─────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────┼────────────────────────────────────────────────────────┤
│ Jorge Semião|Juan J. Rodríguez-Andina|Fabian Vargas|Marcelino Bicho Dos Santos|Isabel C. Teixeira|João Paulo Teixeira                     │ Improving the Tolerance of Pipeline Based Circuits to Power Supply or Temperature Variations.                 │ -2007 │  180843 │ conf/dft/SemiaoRVSTT07         │        1 │           0 │               0 │             4 │                 4 │ inproceedings │ NULL                                    │ NULL                                                                │ DFT                                               │ nán                                                    │
│ Patrice Caire                                                                                                                             │ A Normative Multi-Agent Systems Approach to the Use of Conviviality for Digital Cities.                       │ -2007 │  162991 │ conf/dagstuhl/Caire07          │        2 │           0 │               0 │             7 │                 7 │ inprớcéédings │ NULL                                    │ NULL                                                                │ Normative Multi-agent Systems                     │ Éúrớpéán Grid Cớnféréncé                               │
│ Sundeep B|Andrew Thangaraj                                                                                                                │ Self-Orthogonality of q-Ary Images of qm-Ary Codes and Quantum Code Construction.                             │  2007 │ 2261406 │ journals/tit/BT07              │        0 │           2 │               2 │             9 │                 9 │ árticlé       │ IEEE Transactions on Information Theory │ International Journal of Ambient Computing and Intelligence (IJACI) │ WiMớb                                             │ ACM Symposium on Parallel Algorithms and Architectures │
│ Gerardo Pardo-Castellote                                                                                                                  │ OMG Data-Distribution Service: Architectural Overview.                                                        │ -2003 │  349720 │ conf/icdcsw/Pardo-Castellote03 │        1 │           0 │               0 │            11 │                11 │ inproceedings │ NULL                                    │ NULL                                                                │ ICDCS Workshops                                   │ International Agent Technology Conference              │
│ Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-Soo Kim 0002                                                                                │ Structural Consistency: Enabling XML Keyword Search to Eliminate Spurious Results Consistently                │  2009 │ 1922328 │ journals/corr/abs-0911-4329    │        3 │           5 │               5 │             5 │                 5 │ article       │ CoRR                                    │ International Journal of Wireless Information Networks              │ NULL                                              │ Messung                                                │
│ Bin Liu|David J. Hill|Kok Lay Teo                                                                                                         │ Input-to-state stability for a class of hybrid dynamical systems via hybrid time approach.                    │ -2009 │  883711 │ conf/cdc/LiuHT09               │        1 │           0 │               0 │             5 │                 5 │ inproceedings │ NULL                                    │ NULL                                                                │ NULL                                              │ Messung                                                │
│ A fourth-order compact difference scheme on face centered cubic grids with multigrid method for solving 2D convection diffusion equation. │ Haiwei Sun|Ning Kang|Jun Zhang|Eric S. Carlson                                                                │ -2003 │ 2324621 │ journals/mcs/SunKZC03          │        3 │           6 │               6 │             5 │                 5 │ article       │ Mathematics and Computers in Simulation │ International Transactions on Systems Science and Applications      │ NULL                                              │ Messung                                                │
│ Sang-Heon Lee|Nam-Sung Kim|Heau-Jo Kang|Soon-Gohn Kim                                                                                     │ Performance Improvement of Intelligent UWB-IR Communication System in Multipath Channel.                      │ -2006 │  366780 │ conf/icic/LeeKKK06             │        0 │           0 │               0 │             0 │                 0 │ árticlé       │ NULL                                    │ NULL                                                                │ nán                                               │ NULL                                                   │
│ Eugene Pamba Capo-Chichi|Hervé Guyennet|Jean-Michel Friedt                                                                                │ IEEE 802.15.4 Performance on a Hierarchical Hybrid Sensor Network Platform.                                   │ -2009 │  794722 │ conf/icns/Capo-ChichiGF09      │        2 │           0 │               0 │            15 │                15 │ inprớcéédings │ NULL                                    │ NULL                                                                │ ICNS                                              │ Ásiá-Pácific Wéb Cớnféréncé                            │
│ Feng Wang|Michael J. Hannafin                                                                                                             │ Scaffolding preservice teachers' WebQuest design: a qualitative study.                                        │ -2009 │ 2339884 │ journals/jche/WangH09          │        0 │          10 │              10 │             5 │                 5 │ árticlé       │ J. Computing in Higher Education        │ Journal of Computers                                                │ NULL                                              │ Messung                                                │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │    ·          │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │    ·          │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │    ·          │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │
│ Wenchang Chu|Chenying Wang                                                                                                                │ Bilateral inversions and terminating basic hypergeometric series identities.                                  │  2009 │ 1957806 │ journals/dm/ChuW09             │        2 │          68 │              68 │          1396 │              1396 │ inprớcéédings │ Discrete Mathematics                    │ Journal of Information & Knowledge Management                       │ CSSÉ (4)                                          │ NULL                                                   │
│ Masakatsu Matsuishi|Toru Kitamura                                                                                                         │ Introductory Pre-College Engineering Design Course Based upon Collaborative Learning to High School Students. │ -2006 │  731619 │ conf/sutc/MatsuishiK06         │        0 │           0 │               0 │          1414 │              1414 │ árticlé       │ NULL                                    │ NULL                                                                │ SUTC (2)                                          │ NULL                                                   │
│ Jiri Grim|Jan Hora                                                                                                                        │ Computational Properties of Probabilistic Neural Networks.                                                    │  2010 │  320632 │ conf/icann/GrimH10             │        1 │           0 │               0 │          1416 │              1416 │ inproceedings │ NULL                                    │ NULL                                                                │ ICÁNN (3)                                         │ NULL                                                   │
│ LIV - The Linux Integrated Viruswall.                                                                                                     │ Teobaldo A. Dantas de Medeiros|Paulo S. Motta Pires                                                           │  2004 │  183968 │ conf/dimva/MedeirosP04         │        2 │           0 │               0 │          1419 │              1419 │ inprớcéédings │ NULL                                    │ NULL                                                                │ DIMVÁ                                             │ NULL                                                   │
│ Anish Das Sarma|Xin Luna Dong|Alon Y. Halevy                                                                                              │ Data Modeling in Dataspace Support Platforms.                                                                 │ -2009 │   78605 │ conf/birthday/SarmaDH09        │        1 │           0 │               0 │          1423 │              1423 │ inproceedings │ NULL                                    │ NULL                                                                │ Conceptual Modeling: Foundations and Applications │ NULL                                                   │
│ Efficient Testing of Concurrent Programs with Abstraction-Guided Symbolic Execution.                                                      │ Neha Rungta|Eric G. Mercer|Willem Visser                                                                      │ -2009 │  722399 │ conf/spin/RungtaMV09           │        4 │           0 │               0 │          1425 │              1425 │ phdthesis     │ NULL                                    │ NULL                                                                │ SPIN                                              │ NULL                                                   │
│ Gasper Tkacik|William Bialek                                                                                                              │ Cell Biology: Networks, Regulation and Pathways.                                                              │  2009 │ 2425693 │ reference/complexity/TkacikB09 │        0 │           0 │               0 │          1430 │              1430 │ árticlé       │ NULL                                    │ NULL                                                                │ Éncyclớpédiá ớf Cớmpléxity ánd Systéms Sciéncé    │ NULL                                                   │
│ Neelakantan Sundaresan|Dennis Gannon                                                                                                      │ A Thread Model for Supporting Task and Data Parallelism in Object-Oriented Languages.                         │  1995 │  406516 │ conf/icpp/SundaresanG95        │        1 │           0 │               0 │          1433 │              1433 │ inproceedings │ NULL                                    │ NULL                                                                │ ICPP (2)                                          │ NULL                                                   │
│ Zeeshan Syed|John V. Guttag                                                                                                               │ Prototypical Biological Signals.                                                                              │  2007 │  900353 │ conf/icassp/SyedG07            │        2 │           0 │               0 │          1434 │              1434 │ inprớcéédings │ NULL                                    │ NULL                                                                │ ICÁSSP (1)                                        │ NULL                                                   │
│ Design of PCI 2.2 Target Controller to Support Prefetch Request.                                                                          │ Eugin Hyun|Kyo-Yong Han|Kwang-Su Seong                                                                        │  2005 │   99433 │ conf/cdes/HyunHS05             │        1 │           0 │               0 │          1299 │              1299 │ inproceedings │ NULL                                    │ NULL                                                                │ CDES                                              │ NULL                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┴─────────┴────────────────────────────────┴──────────┴─────────────┴─────────────────┴───────────────┴───────────────────┴───────────────┴─────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────┴────────────────────────────────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 15 columns

In [22]:
con.query("""
    SELECT 'pauthor' AS column_name, COUNT(*) AS null_count FROM df_new WHERE pauthor IS NULL OR pauthor = '' OR pauthor = 'nan'
    UNION ALL
    SELECT 'ptitle',                  COUNT(*) FROM df_new WHERE ptitle IS NULL OR ptitle = '' OR ptitle = 'nan'
    UNION ALL
    SELECT 'pyear',                   COUNT(*) FROM df_new WHERE pyear IS NULL
    UNION ALL
    SELECT 'pid',                     COUNT(*) FROM df_new WHERE pid IS NULL
    UNION ALL
    SELECT 'pkey',                    COUNT(*) FROM df_new WHERE pkey IS NULL
    UNION ALL
    SELECT 'ptype',                   COUNT(*) FROM df_new WHERE ptype IS NULL
""").show()

┌─────────────┬────────────┐
│ column_name │ null_count │
│   varchar   │   int64    │
├─────────────┼────────────┤
│ pauthor     │          0 │
│ ptitle      │          0 │
│ pyear       │          0 │
│ pid         │          0 │
│ pkey        │          0 │
│ ptype       │          0 │
└─────────────┴────────────┘

## Booktitle

In [23]:
# booktitle and booktitle full check for NULL, nan and Messung values
print("Checking booktitle for NULL, 'nán', and 'Messung' values:")
con.query("""
    SELECT COUNT(*) AS null_count
    FROM df_new
    WHERE booktitle IS NULL OR booktitle = 'nán' OR booktitle = 'Messung'
    """).show()

print("Checking booktitlefull for NULL, 'nán', and 'Messung' values:")
con.query("""
    SELECT COUNT(*) AS null_count
    FROM df_new
    WHERE booktitlefull IS NULL OR booktitlefull = 'nán' OR booktitlefull = 'Messung'
    """).show()

Checking booktitle for NULL, 'nán', and 'Messung' values:
┌────────────┐
│ null_count │
│   int64    │
├────────────┤
│       8040 │
└────────────┘

Checking booktitlefull for NULL, 'nán', and 'Messung' values:
┌────────────┐
│ null_count │
│   int64    │
├────────────┤
│      11287 │
└────────────┘

Booktitlefull has 7 more missing values than booktitle, so lets check where those occur:

In [24]:
con.query("""
    SELECT booktitle, booktitlefull, COUNT(*) AS cnt
    FROM df_new
    WHERE (booktitlefull IS NULL OR booktitlefull = 'nán' OR booktitlefull = 'Messung')
      AND NOT (booktitle IS NULL OR booktitle = 'nán' OR booktitle = 'Messung')
    GROUP BY booktitle, booktitlefull
    ORDER BY cnt DESC
""").show()

┌───────────────────────────────────────────────┬───────────────┬───────┐
│                   booktitle                   │ booktitlefull │  cnt  │
│                    varchar                    │    varchar    │ int64 │
├───────────────────────────────────────────────┼───────────────┼───────┤
│ CVPR                                          │ NULL          │    19 │
│ STOC                                          │ NULL          │    12 │
│ MICAI                                         │ NULL          │    10 │
│ CIARP                                         │ NULL          │    10 │
│ ACM Great Lakes Symposium on VLSI             │ NULL          │     9 │
│ ICIAP                                         │ NULL          │     9 │
│ CADE                                          │ NULL          │     9 │
│ DSN                                           │ NULL          │     9 │
│ Advances in Computer Entertainment Technology │ NULL          │     9 │
│ ISMIR                                         │ NULL          │     8 │
│   ·                                           │  ·            │     · │
│   ·                                           │  ·            │     · │
│   ·                                           │  ·            │     · │
│ CIAO! / EOMAS                                 │ NULL          │     1 │
│ GIR                                           │ NULL          │     1 │
│ IWSM/Metrikon/Mensura                         │ NULL          │     1 │
│ PODDP                                         │ NULL          │     1 │
│ SERVICES II                                   │ NULL          │     1 │
│ CIT (1)                                       │ NULL          │     1 │
│ RFIDSec                                       │ NULL          │     1 │
│ ICIRA (1)                                     │ NULL          │     1 │
│ ERSA                                          │ NULL          │     1 │
│ EuroVis                                       │ NULL          │     1 │
└───────────────────────────────────────────────┴───────────────┴───────┘
  1637 rows (20 shown)                                        3 columns

In [25]:
con.query("""
    SELECT booktitle, booktitlefull
    FROM df_new
    WHERE booktitle = 'DFT'
""").show()

┌───────────┬───────────────┐
│ booktitle │ booktitlefull │
│  varchar  │    varchar    │
├───────────┼───────────────┤
│ DFT       │ nán           │
│ DFT       │ nán           │
│ DFT       │ nán           │
│ DFT       │ nán           │
│ DFT       │ nán           │
│ DFT       │ nán           │
│ DFT       │ nán           │
└───────────┴───────────────┘

So whenever booktitle has DFT theres a nan value in booktitle full. One approach is to make those nan values in booktitlefull also equal to DFT

In [26]:
# duckdb can't update a view result directly, so we will do the update in pandas and then re-register the DataFrame
df_new_pandas = df_new.to_df()
mask = (df_new_pandas['booktitlefull'] == 'nán') & (df_new_pandas['booktitle'] == 'DFT')
df_new_pandas.loc[mask, 'booktitlefull'] = 'DFT'
con.register("df_new", df_new_pandas)

print("Checking AGAIN booktitlefull for NULL, 'nán', and 'Messung' values:")
con.query("""
    SELECT COUNT(*) AS null_count
    FROM df_new
    WHERE booktitlefull IS NULL OR booktitlefull = 'nán' OR booktitlefull = 'Messung'
    """).show()

Checking AGAIN booktitlefull for NULL, 'nán', and 'Messung' values:
┌────────────┐
│ null_count │
│   int64    │
├────────────┤
│      11280 │
└────────────┘

Lastly we can check if the rows in which booktitle has a missing value are the same as when booktitlefull has missing values

In [27]:
con.query("""
    SELECT COUNT(*) AS only_booktitle_missing
    FROM df_new
    WHERE (booktitle IS NULL OR booktitle = 'nán' OR booktitle = 'Messung')
      AND NOT (booktitlefull IS NULL OR booktitlefull = 'nán' OR booktitlefull = 'Messung')
""").show()

┌────────────────────────┐
│ only_booktitle_missing │
│         int64          │
├────────────────────────┤
│                      0 │
└────────────────────────┘

They are the same. We will make them NULL later

## Journal
Repeating the same process above but for pjournal and pjournalfull

In [28]:
print("Checking journal for NULL, 'nán', 'nan', 'NaN', and 'Messung' values:")
con.query("""
    SELECT COUNT(*) AS null_count
    FROM df_new
    WHERE journal IS NULL OR journal = 'nán' OR journal = 'nan' OR journal = 'NaN' OR journal = 'Messung'
    """).show()

print("Checking journalfull for NULL, 'nán', 'nan', 'NaN', and 'Messung' values:")
con.query("""
    SELECT COUNT(*) AS null_count
    FROM df_new
    WHERE journalfull IS NULL OR journalfull = 'nán' OR journalfull = 'nan' OR journalfull = 'NaN' OR journalfull = 'Messung'
    """).show()

Checking journal for NULL, 'nán', 'nan', 'NaN', and 'Messung' values:
┌────────────┐
│ null_count │
│   int64    │
├────────────┤
│      11610 │
└────────────┘

Checking journalfull for NULL, 'nán', 'nan', 'NaN', and 'Messung' values:
┌────────────┐
│ null_count │
│   int64    │
├────────────┤
│      15128 │
└────────────┘

They have the same number of values, lets check if the entries match

In [29]:
con.query("""
    SELECT COUNT(*) AS only_journal_missing
    FROM df_new
    WHERE (journal IS NULL OR journal = 'nán' OR journal = 'nan' OR journal = 'NaN' OR journal = 'Messung')
      AND NOT (journalfull IS NULL OR journalfull = 'nán' OR journalfull = 'nan' OR journalfull = 'NaN' OR journalfull = 'Messung')
""").show()

┌──────────────────────┐
│ only_journal_missing │
│        int64         │
├──────────────────────┤
│                    0 │
└──────────────────────┘

Okay here they also occur in the same rows. Lets also make these all NULL

In [30]:
missing_vals = ['nán', 'nan', 'NaN', 'Messung']

df_new_pandas['booktitle'] = df_new_pandas['booktitle'].replace(missing_vals, None)
df_new_pandas['booktitlefull'] = df_new_pandas['booktitlefull'].replace(missing_vals, None)
df_new_pandas['journal'] = df_new_pandas['journal'].replace(missing_vals, None)
df_new_pandas['journalfull'] = df_new_pandas['journalfull'].replace(missing_vals, None)

con.register("df_new", df_new_pandas)

In [31]:
df_new_pandas.head()

,pauthor,ptitle,pyear,pid,pkey,ptype_id,pjournal_id,pjournalfull_id,pbooktitle_id,pbooktitlefull_id,ptype,journal,journalfull,booktitle,booktitlefull
0,Jorge Semião|Juan J. Rodríguez-Andina|Fabian V...,Improving the Tolerance of Pipeline Based Circ...,-2007,180843,conf/dft/SemiaoRVSTT07,1,0,0,4,4,inproceedings,NaN,NaN,DFT,DFT
1,Patrice Caire,A Normative Multi-Agent Systems Approach to th...,-2007,162991,conf/dagstuhl/Caire07,2,0,0,7,7,inprớcéédings,NaN,NaN,Normative Multi-agent Systems,Éúrớpéán Grid Cớnféréncé
2,Sundeep B|Andrew Thangaraj,Self-Orthogonality of q-Ary Images of qm-Ary C...,2007,2261406,journals/tit/BT07,0,2,2,9,9,árticlé,IEEE Transactions on Information Theory,International Journal of Ambient Computing and...,WiMớb,ACM Symposium on Parallel Algorithms and Archi...
3,Gerardo Pardo-Castellote,OMG Data-Distribution Service: Architectural O...,-2003,349720,conf/icdcsw/Pardo-Castellote03,1,0,0,11,11,inproceedings,NaN,NaN,ICDCS Workshops,International Agent Technology Conference
4,Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-...,Structural Consistency: Enabling XML Keyword S...,2009,1922328,journals/corr/abs-0911-4329,3,5,5,5,5,article,CoRR,International Journal of Wireless Information ...,NaN,None

In [32]:
con.query("""
    SELECT 'booktitle'     AS column_name, COUNT(*) AS null_count FROM df_new WHERE booktitle IS NULL
    UNION ALL
    SELECT 'booktitlefull' AS column_name, COUNT(*) AS null_count FROM df_new WHERE booktitlefull IS NULL
    UNION ALL
    SELECT 'journal'       AS column_name, COUNT(*) AS null_count FROM df_new WHERE journal IS NULL
    UNION ALL
    SELECT 'journalfull'   AS column_name, COUNT(*) AS null_count FROM df_new WHERE journalfull IS NULL
""").show()

┌───────────────┬────────────┐
│  column_name  │ null_count │
│    varchar    │   int64    │
├───────────────┼────────────┤
│ booktitle     │       8040 │
│ booktitlefull │      11280 │
│ journal       │      11610 │
│ journalfull   │      15128 │
└───────────────┴────────────┘

In [33]:
con.query("SELECT * FROM df_new").show()

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┬────────────────────────────────┬──────────┬─────────────┬─────────────────┬───────────────┬───────────────────┬───────────────┬─────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────┬────────────────────────────────────────────────────────┐
│                                                                  pauthor                                                                  │                                                    ptitle                                                     │ pyear │   pid   │              pkey              │ ptype_id │ pjournal_id │ pjournalfull_id │ pbooktitle_id │ pbooktitlefull_id │     ptype     │                 journal                 │                             journalfull                             │                     booktitle                     │                     booktitlefull                      │
│                                                                  varchar                                                                  │                                                    varchar                                                    │ int64 │  int64  │            varchar             │  int64   │    int64    │      int64      │     int64     │       int64       │    varchar    │                 varchar                 │                               varchar                               │                      varchar                      │                        varchar                         │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼─────────┼────────────────────────────────┼──────────┼─────────────┼─────────────────┼───────────────┼───────────────────┼───────────────┼─────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────┼────────────────────────────────────────────────────────┤
│ Jorge Semião|Juan J. Rodríguez-Andina|Fabian Vargas|Marcelino Bicho Dos Santos|Isabel C. Teixeira|João Paulo Teixeira                     │ Improving the Tolerance of Pipeline Based Circuits to Power Supply or Temperature Variations.                 │ -2007 │  180843 │ conf/dft/SemiaoRVSTT07         │        1 │           0 │               0 │             4 │                 4 │ inproceedings │ NULL                                    │ NULL                                                                │ DFT                                               │ DFT                                                    │
│ Patrice Caire                                                                                                                             │ A Normative Multi-Agent Systems Approach to the Use of Conviviality for Digital Cities.                       │ -2007 │  162991 │ conf/dagstuhl/Caire07          │        2 │           0 │               0 │             7 │                 7 │ inprớcéédings │ NULL                                    │ NULL                                                                │ Normative Multi-agent Systems                     │ Éúrớpéán Grid Cớnféréncé                               │
│ Sundeep B|Andrew Thangaraj                                                                                                                │ Self-Orthogonality of q-Ary Images of qm-Ary Codes and Quantum Code Construction.                             │  2007 │ 2261406 │ journals/tit/BT07              │        0 │           2 │               2 │             9 │                 9 │ árticlé       │ IEEE Transactions on Information Theory │ International Journal of Ambient Computing and Intelligence (IJACI) │ WiMớb                                             │ ACM Symposium on Parallel Algorithms and Architectures │
│ Gerardo Pardo-Castellote                                                                                                                  │ OMG Data-Distribution Service: Architectural Overview.                                                        │ -2003 │  349720 │ conf/icdcsw/Pardo-Castellote03 │        1 │           0 │               0 │            11 │                11 │ inproceedings │ NULL                                    │ NULL                                                                │ ICDCS Workshops                                   │ International Agent Technology Conference              │
│ Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-Soo Kim 0002                                                                                │ Structural Consistency: Enabling XML Keyword Search to Eliminate Spurious Results Consistently                │  2009 │ 1922328 │ journals/corr/abs-0911-4329    │        3 │           5 │               5 │             5 │                 5 │ article       │ CoRR                                    │ International Journal of Wireless Information Networks              │ NULL                                              │ NULL                                                   │
│ Bin Liu|David J. Hill|Kok Lay Teo                                                                                                         │ Input-to-state stability for a class of hybrid dynamical systems via hybrid time approach.                    │ -2009 │  883711 │ conf/cdc/LiuHT09               │        1 │           0 │               0 │             5 │                 5 │ inproceedings │ NULL                                    │ NULL                                                                │ NULL                                              │ NULL                                                   │
│ A fourth-order compact difference scheme on face centered cubic grids with multigrid method for solving 2D convection diffusion equation. │ Haiwei Sun|Ning Kang|Jun Zhang|Eric S. Carlson                                                                │ -2003 │ 2324621 │ journals/mcs/SunKZC03          │        3 │           6 │               6 │             5 │                 5 │ article       │ Mathematics and Computers in Simulation │ International Transactions on Systems Science and Applications      │ NULL                                              │ NULL                                                   │
│ Sang-Heon Lee|Nam-Sung Kim|Heau-Jo Kang|Soon-Gohn Kim                                                                                     │ Performance Improvement of Intelligent UWB-IR Communication System in Multipath Channel.                      │ -2006 │  366780 │ conf/icic/LeeKKK06             │        0 │           0 │               0 │             0 │                 0 │ árticlé       │ NULL                                    │ NULL                                                                │ NULL                                              │ NULL                                                   │
│ Eugene Pamba Capo-Chichi|Hervé Guyennet|Jean-Michel Friedt                                                                                │ IEEE 802.15.4 Performance on a Hierarchical Hybrid Sensor Network Platform.                                   │ -2009 │  794722 │ conf/icns/Capo-ChichiGF09      │        2 │           0 │               0 │            15 │                15 │ inprớcéédings │ NULL                                    │ NULL                                                                │ ICNS                                              │ Ásiá-Pácific Wéb Cớnféréncé                            │
│ Feng Wang|Michael J. Hannafin                                                                                                             │ Scaffolding preservice teachers' WebQuest design: a qualitative study.                                        │ -2009 │ 2339884 │ journals/jche/WangH09          │        0 │          10 │              10 │             5 │                 5 │ árticlé       │ J. Computing in Higher Education        │ Journal of Computers                                                │ NULL                                              │ NULL                                                   │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │    ·          │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │    ·          │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │    ·          │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │
│ Wenchang Chu|Chenying Wang                                                                                                                │ Bilateral inversions and terminating basic hypergeometric series identities.                                  │  2009 │ 1957806 │ journals/dm/ChuW09             │        2 │          68 │              68 │          1396 │              1396 │ inprớcéédings │ Discrete Mathematics                    │ Journal of Information & Knowledge Management                       │ CSSÉ (4)                                          │ NULL                                                   │
│ Masakatsu Matsuishi|Toru Kitamura                                                                                                         │ Introductory Pre-College Engineering Design Course Based upon Collaborative Learning to High School Students. │ -2006 │  731619 │ conf/sutc/MatsuishiK06         │        0 │           0 │               0 │          1414 │              1414 │ árticlé       │ NULL                                    │ NULL                                                                │ SUTC (2)                                          │ NULL                                                   │
│ Jiri Grim|Jan Hora                                                                                                                        │ Computational Properties of Probabilistic Neural Networks.                                                    │  2010 │  320632 │ conf/icann/GrimH10             │        1 │           0 │               0 │          1416 │              1416 │ inproceedings │ NULL                                    │ NULL                                                                │ ICÁNN (3)                                         │ NULL                                                   │
│ LIV - The Linux Integrated Viruswall.                                                                                                     │ Teobaldo A. Dantas de Medeiros|Paulo S. Motta Pires                                                           │  2004 │  183968 │ conf/dimva/MedeirosP04         │        2 │           0 │               0 │          1419 │              1419 │ inprớcéédings │ NULL                                    │ NULL                                                                │ DIMVÁ                                             │ NULL                                                   │
│ Anish Das Sarma|Xin Luna Dong|Alon Y. Halevy                                                                                              │ Data Modeling in Dataspace Support Platforms.                                                                 │ -2009 │   78605 │ conf/birthday/SarmaDH09        │        1 │           0 │               0 │          1423 │              1423 │ inproceedings │ NULL                                    │ NULL                                                                │ Conceptual Modeling: Foundations and Applications │ NULL                                                   │
│ Efficient Testing of Concurrent Programs with Abstraction-Guided Symbolic Execution.                                                      │ Neha Rungta|Eric G. Mercer|Willem Visser                                                                      │ -2009 │  722399 │ conf/spin/RungtaMV09           │        4 │           0 │               0 │          1425 │              1425 │ phdthesis     │ NULL                                    │ NULL                                                                │ SPIN                                              │ NULL                                                   │
│ Gasper Tkacik|William Bialek                                                                                                              │ Cell Biology: Networks, Regulation and Pathways.                                                              │  2009 │ 2425693 │ reference/complexity/TkacikB09 │        0 │           0 │               0 │          1430 │              1430 │ árticlé       │ NULL                                    │ NULL                                                                │ Éncyclớpédiá ớf Cớmpléxity ánd Systéms Sciéncé    │ NULL                                                   │
│ Neelakantan Sundaresan|Dennis Gannon                                                                                                      │ A Thread Model for Supporting Task and Data Parallelism in Object-Oriented Languages.                         │  1995 │  406516 │ conf/icpp/SundaresanG95        │        1 │           0 │               0 │          1433 │              1433 │ inproceedings │ NULL                                    │ NULL                                                                │ ICPP (2)                                          │ NULL                                                   │
│ Zeeshan Syed|John V. Guttag                                                                                                               │ Prototypical Biological Signals.                                                                              │  2007 │  900353 │ conf/icassp/SyedG07            │        2 │           0 │               0 │          1434 │              1434 │ inprớcéédings │ NULL                                    │ NULL                                                                │ ICÁSSP (1)                                        │ NULL                                                   │
│ Design of PCI 2.2 Target Controller to Support Prefetch Request.                                                                          │ Eugin Hyun|Kyo-Yong Han|Kwang-Su Seong                                                                        │  2005 │   99433 │ conf/cdes/HyunHS05             │        1 │           0 │               0 │          1299 │              1299 │ inproceedings │ NULL                                    │ NULL                                                                │ CDES                                              │ NULL                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┴─────────┴────────────────────────────────┴──────────┴─────────────┴─────────────────┴───────────────┴───────────────────┴───────────────┴─────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────┴────────────────────────────────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 15 columns

In [34]:
df_new_pandas.head(10)

,pauthor,ptitle,pyear,pid,pkey,ptype_id,pjournal_id,pjournalfull_id,pbooktitle_id,pbooktitlefull_id,ptype,journal,journalfull,booktitle,booktitlefull
0,Jorge Semião|Juan J. Rodríguez-Andina|Fabian V...,Improving the Tolerance of Pipeline Based Circ...,-2007,180843,conf/dft/SemiaoRVSTT07,1,0,0,4,4,inproceedings,NaN,NaN,DFT,DFT
1,Patrice Caire,A Normative Multi-Agent Systems Approach to th...,-2007,162991,conf/dagstuhl/Caire07,2,0,0,7,7,inprớcéédings,NaN,NaN,Normative Multi-agent Systems,Éúrớpéán Grid Cớnféréncé
2,Sundeep B|Andrew Thangaraj,Self-Orthogonality of q-Ary Images of qm-Ary C...,2007,2261406,journals/tit/BT07,0,2,2,9,9,árticlé,IEEE Transactions on Information Theory,International Journal of Ambient Computing and...,WiMớb,ACM Symposium on Parallel Algorithms and Archi...
3,Gerardo Pardo-Castellote,OMG Data-Distribution Service: Architectural O...,-2003,349720,conf/icdcsw/Pardo-Castellote03,1,0,0,11,11,inproceedings,NaN,NaN,ICDCS Workshops,International Agent Technology Conference
4,Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-...,Structural Consistency: Enabling XML Keyword S...,2009,1922328,journals/corr/abs-0911-4329,3,5,5,5,5,article,CoRR,International Journal of Wireless Information ...,NaN,None
5,Bin Liu|David J. Hill|Kok Lay Teo,Input-to-state stability for a class of hybrid...,-2009,883711,conf/cdc/LiuHT09,1,0,0,5,5,inproceedings,NaN,NaN,NaN,None
6,A fourth-order compact difference scheme on fa...,Haiwei Sun|Ning Kang|Jun Zhang|Eric S. Carlson,-2003,2324621,journals/mcs/SunKZC03,3,6,6,5,5,article,Mathematics and Computers in Simulation,International Transactions on Systems Science ...,NaN,None
7,Sang-Heon Lee|Nam-Sung Kim|Heau-Jo Kang|Soon-G...,Performance Improvement of Intelligent UWB-IR ...,-2006,366780,conf/icic/LeeKKK06,0,0,0,0,0,árticlé,NaN,NaN,None,NaN
8,Eugene Pamba Capo-Chichi|Hervé Guyennet|Jean-M...,IEEE 802.15.4 Performance on a Hierarchical Hy...,-2009,794722,conf/icns/Capo-ChichiGF09,2,0,0,15,15,inprớcéédings,NaN,NaN,ICNS,Ásiá-Pácific Wéb Cớnféréncé
9,Feng Wang|Michael J. Hannafin,Scaffolding preservice teachers' WebQuest desi...,-2009,2339884,journals/jche/WangH09,0,10,10,5,5,árticlé,J. Computing in Higher Education,Journal of Computers,NaN,None

#### Cleaning Strings of Booktitles

In [35]:
import unicodedata
import re

In [36]:
def clean_string(s):
    if s is None or pd.isnull(s):
        return s

    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))

    s = s.replace("-", " ")
    return s.strip().lower()

In [37]:
for id, name in df_new_pandas['booktitlefull'].items():
    #print(df_new_pandas.loc[id, 'booktitlefull'])
    df_new_pandas.loc[id, 'booktitlefull'] = clean_string(name)

for id, name in df_new_pandas['booktitle'].items():
    df_new_pandas.loc[id, 'booktitle'] = clean_string(name)

df_new_pandas.head()

,pauthor,ptitle,pyear,pid,pkey,ptype_id,pjournal_id,pjournalfull_id,pbooktitle_id,pbooktitlefull_id,ptype,journal,journalfull,booktitle,booktitlefull
0,Jorge Semião|Juan J. Rodríguez-Andina|Fabian V...,Improving the Tolerance of Pipeline Based Circ...,-2007,180843,conf/dft/SemiaoRVSTT07,1,0,0,4,4,inproceedings,NaN,NaN,dft,dft
1,Patrice Caire,A Normative Multi-Agent Systems Approach to th...,-2007,162991,conf/dagstuhl/Caire07,2,0,0,7,7,inprớcéédings,NaN,NaN,normative multi agent systems,european grid conference
2,Sundeep B|Andrew Thangaraj,Self-Orthogonality of q-Ary Images of qm-Ary C...,2007,2261406,journals/tit/BT07,0,2,2,9,9,árticlé,IEEE Transactions on Information Theory,International Journal of Ambient Computing and...,wimob,acm symposium on parallel algorithms and archi...
3,Gerardo Pardo-Castellote,OMG Data-Distribution Service: Architectural O...,-2003,349720,conf/icdcsw/Pardo-Castellote03,1,0,0,11,11,inproceedings,NaN,NaN,icdcs workshops,international agent technology conference
4,Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-...,Structural Consistency: Enabling XML Keyword S...,2009,1922328,journals/corr/abs-0911-4329,3,5,5,5,5,article,CoRR,International Journal of Wireless Information ...,NaN,None

In [38]:
def extract_abbreviations(name):
    if not name or pd.isnull(name):
        return None

    # Extracting ABBREV in 'Full Title (ABBREV)'
    match = re.search(r'\(([^)]+)\)$', name.strip())
    if match:
        return match.group(1).strip()
   
   # Extracting ABBREV in'Full Title - ABBREV'
    match = re.search(r'\s[-–]\s([A-Z][^\s].*)$', name.strip())
    if match:
        return match.group(1).strip()
    
    return None

In [39]:
journal_abbreviations = {k: extract_abbreviations(name) for k, name in pjournalfull.items()}

In [40]:
def clean_journal_titles(name):

    if not name or pd.isnull(name):
        return name
    
    # remove abbreviations and acronyms 
    match = re.search(r'\(([^)]+)\)$', name.strip())
    if match:
        name = name.replace(match.group(0), "")
    
    match = re.search(r'\s[-–]\s([A-Z][^\s].*)$', name.strip())
    if match:
        name = name.replace(match.group(0), "")

    # then cleaning string normally
    cleaned = clean_string(name)
    return cleaned

In [41]:
for id, name in df_new_pandas['journal'].items():
    #print(df_new_pandas.loc[id, 'booktitlefull'])
    df_new_pandas.loc[id, 'journal'] = clean_string(name)

for id, name in df_new_pandas['journalfull'].items():
    df_new_pandas.loc[id, 'journalfull'] = clean_string(name)

for id, abb in journal_abbreviations.items():
    df_new_pandas.loc[id, 'journal_abbreviation'] = clean_string(abb)

In [42]:
df_new_pandas.head()

,pauthor,ptitle,pyear,pid,pkey,ptype_id,pjournal_id,pjournalfull_id,pbooktitle_id,pbooktitlefull_id,ptype,journal,journalfull,booktitle,booktitlefull,journal_abbreviation
0,Jorge Semião|Juan J. Rodríguez-Andina|Fabian V...,Improving the Tolerance of Pipeline Based Circ...,-2007,180843,conf/dft/SemiaoRVSTT07,1,0,0,4,4,inproceedings,NaN,NaN,dft,dft,None
1,Patrice Caire,A Normative Multi-Agent Systems Approach to th...,-2007,162991,conf/dagstuhl/Caire07,2,0,0,7,7,inprớcéédings,NaN,NaN,normative multi agent systems,european grid conference,None
2,Sundeep B|Andrew Thangaraj,Self-Orthogonality of q-Ary Images of qm-Ary C...,2007,2261406,journals/tit/BT07,0,2,2,9,9,árticlé,ieee transactions on information theory,international journal of ambient computing and...,wimob,acm symposium on parallel algorithms and archi...,ijaci
3,Gerardo Pardo-Castellote,OMG Data-Distribution Service: Architectural O...,-2003,349720,conf/icdcsw/Pardo-Castellote03,1,0,0,11,11,inproceedings,NaN,NaN,icdcs workshops,international agent technology conference,monet
4,Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-...,Structural Consistency: Enabling XML Keyword S...,2009,1922328,journals/corr/abs-0911-4329,3,5,5,5,5,article,corr,international journal of wireless information ...,NaN,None,None

In [43]:
con.register("df_new", df_new_pandas)

## New DuckDB Table

Currently this table was still registered to a pandas dataframe. So I'm creating a new duckdb table to make the next changes on that directly.

In [44]:
con.query("""
    CREATE OR REPLACE TABLE ducktable AS
    SELECT * FROM df_new
""")

## PYear 
Taking the absolute value of the negative years

In [45]:
con.query("""
    UPDATE ducktable
    SET pyear = ABS(pyear)
    WHERE pyear < 0
""")

## Publication Type: ptype_id

Changing the typeids using a CASE statement: 
remap corrupted IDs to canonical ones: `{0→3, 2→1, 5→6, 7→8}`

In [46]:
con.query(""" SELECT COUNT(*) FROM ducktable""").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        17165 │
└──────────────┘

In [47]:
# first I will drop the existing column of ptype
con.query("""ALTER TABLE ducktable DROP COLUMN ptype""")

# then I will alter the values of the ids to the correct ones
con.query("""
    UPDATE ducktable
    SET ptype_id = CASE ptype_id
        WHEN 0 THEN 3
        WHEN 2 THEN 1
        WHEN 5 THEN 6
        WHEN 7 THEN 8
        ELSE ptype_id
    END
""")

# then I will join with the ptype_df to get the correct ptype names
con.query("""
    CREATE OR REPLACE TABLE ducktable AS
    SELECT ducktable.*, ptype_df.name AS ptype
    FROM ducktable
    LEFT JOIN ptype_df ON ducktable.ptype_id = ptype_df.id
""")

In [48]:
con.query(""" SELECT COUNT(*) FROM ducktable""").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        17165 │
└──────────────┘

In [50]:
con.query(""" SELECT * FROM ducktable""").show()

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┬────────────────────────────────┬──────────┬─────────────┬─────────────────┬───────────────┬───────────────────┬─────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────┬────────────────────────────────────────────────────────┬──────────────────────┬───────────────┐
│                                                                  pauthor                                                                  │                                                    ptitle                                                     │ pyear │   pid   │              pkey              │ ptype_id │ pjournal_id │ pjournalfull_id │ pbooktitle_id │ pbooktitlefull_id │                 journal                 │                             journalfull                             │                     booktitle                     │                     booktitlefull                      │ journal_abbreviation │     ptype     │
│                                                                  varchar                                                                  │                                                    varchar                                                    │ int64 │  int64  │            varchar             │  int64   │    int64    │      int64      │     int64     │       int64       │                 varchar                 │                               varchar                               │                      varchar                      │                        varchar                         │       varchar        │    varchar    │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼─────────┼────────────────────────────────┼──────────┼─────────────┼─────────────────┼───────────────┼───────────────────┼─────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼──────────────────────┼───────────────┤
│ Jorge Semião|Juan J. Rodríguez-Andina|Fabian Vargas|Marcelino Bicho Dos Santos|Isabel C. Teixeira|João Paulo Teixeira                     │ Improving the Tolerance of Pipeline Based Circuits to Power Supply or Temperature Variations.                 │  2007 │  180843 │ conf/dft/SemiaoRVSTT07         │        1 │           0 │               0 │             4 │                 4 │ NULL                                    │ NULL                                                                │ dft                                               │ dft                                                    │ NULL                 │ inproceedings │
│ Patrice Caire                                                                                                                             │ A Normative Multi-Agent Systems Approach to the Use of Conviviality for Digital Cities.                       │  2007 │  162991 │ conf/dagstuhl/Caire07          │        1 │           0 │               0 │             7 │                 7 │ NULL                                    │ NULL                                                                │ normative multi agent systems                     │ european grid conference                               │ NULL                 │ inproceedings │
│ Sundeep B|Andrew Thangaraj                                                                                                                │ Self-Orthogonality of q-Ary Images of qm-Ary Codes and Quantum Code Construction.                             │  2007 │ 2261406 │ journals/tit/BT07              │        3 │           2 │               2 │             9 │                 9 │ ieee transactions on information theory │ international journal of ambient computing and intelligence (ijaci) │ wimob                                             │ acm symposium on parallel algorithms and architectures │ ijaci                │ article       │
│ Gerardo Pardo-Castellote                                                                                                                  │ OMG Data-Distribution Service: Architectural Overview.                                                        │  2003 │  349720 │ conf/icdcsw/Pardo-Castellote03 │        1 │           0 │               0 │            11 │                11 │ NULL                                    │ NULL                                                                │ icdcs workshops                                   │ international agent technology conference              │ monet                │ inproceedings │
│ Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-Soo Kim 0002                                                                                │ Structural Consistency: Enabling XML Keyword Search to Eliminate Spurious Results Consistently                │  2009 │ 1922328 │ journals/corr/abs-0911-4329    │        3 │           5 │               5 │             5 │                 5 │ corr                                    │ international journal of wireless information networks              │ NULL                                              │ NULL                                                   │ NULL                 │ article       │
│ Bin Liu|David J. Hill|Kok Lay Teo                                                                                                         │ Input-to-state stability for a class of hybrid dynamical systems via hybrid time approach.                    │  2009 │  883711 │ conf/cdc/LiuHT09               │        1 │           0 │               0 │             5 │                 5 │ NULL                                    │ NULL                                                                │ NULL                                              │ NULL                                                   │ NULL                 │ inproceedings │
│ A fourth-order compact difference scheme on face centered cubic grids with multigrid method for solving 2D convection diffusion equation. │ Haiwei Sun|Ning Kang|Jun Zhang|Eric S. Carlson                                                                │  2003 │ 2324621 │ journals/mcs/SunKZC03          │        3 │           6 │               6 │             5 │                 5 │ mathematics and computers in simulation │ international transactions on systems science and applications      │ NULL                                              │ NULL                                                   │ NULL                 │ article       │
│ Sang-Heon Lee|Nam-Sung Kim|Heau-Jo Kang|Soon-Gohn Kim                                                                                     │ Performance Improvement of Intelligent UWB-IR Communication System in Multipath Channel.                      │  2006 │  366780 │ conf/icic/LeeKKK06             │        3 │           0 │               0 │             0 │                 0 │ NULL                                    │ NULL                                                                │ NULL                                              │ NULL                                                   │ NULL                 │ article       │
│ Eugene Pamba Capo-Chichi|Hervé Guyennet|Jean-Michel Friedt                                                                                │ IEEE 802.15.4 Performance on a Hierarchical Hybrid Sensor Network Platform.                                   │  2009 │  794722 │ conf/icns/Capo-ChichiGF09      │        1 │           0 │               0 │            15 │                15 │ NULL                                    │ NULL                                                                │ icns                                              │ asia pacific web conference                            │ ijbra                │ inproceedings │
│ Feng Wang|Michael J. Hannafin                                                                                                             │ Scaffolding preservice teachers' WebQuest design: a qualitative study.                                        │  2009 │ 2339884 │ journals/jche/WangH09          │        3 │          10 │              10 │             5 │                 5 │ j. computing in higher education        │ journal of computers                                                │ NULL                                              │ NULL                                                   │ ijhpcn               │ article       │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │  ·                   │    ·          │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │  ·                   │    ·          │
│             ·                                                                                                                             │                                   ·                                                                           │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │  ·                   │    ·          │
│ Wenchang Chu|Chenying Wang                                                                                                                │ Bilateral inversions and terminating basic hypergeometric series identities.                                  │  2009 │ 1957806 │ journals/dm/ChuW09             │        1 │          68 │              68 │          1396 │              1396 │ discrete mathematics                    │ journal of information & knowledge management                       │ csse (4)                                          │ NULL                                                   │ NULL                 │ inproceedings │
│ Masakatsu Matsuishi|Toru Kitamura                                                                                                         │ Introductory Pre-College Engineering Design Course Based upon Collaborative Learning to High School Students. │  2006 │  731619 │ conf/sutc/MatsuishiK06         │        3 │           0 │               0 │          1414 │              1414 │ NULL                                    │ NULL                                                                │ sutc (2)                                          │ NULL                                                   │ NULL                 │ article       │
│ Jiri Grim|Jan Hora                                                                                                                        │ Computational Properties of Probabilistic Neural Networks.                                                    │  2010 │  320632 │ conf/icann/GrimH10             │        1 │           0 │               0 │          1416 │              1416 │ NULL                                    │ NULL                                                                │ icann (3)                                         │ NULL                                                   │ NULL                 │ inproceedings │
│ LIV - The Linux Integrated Viruswall.                                                                                                     │ Teobaldo A. Dantas de Medeiros|Paulo S. Motta Pires                                                           │  2004 │  183968 │ conf/dimva/MedeirosP04         │        1 │           0 │               0 │          1419 │              1419 │ NULL                                    │ NULL                                                                │ dimva                                             │ NULL                                                   │ NULL                 │ inproceedings │
│ Anish Das Sarma|Xin Luna Dong|Alon Y. Halevy                                                                                              │ Data Modeling in Dataspace Support Platforms.                                                                 │  2009 │   78605 │ conf/birthday/SarmaDH09        │        1 │           0 │               0 │          1423 │              1423 │ NULL                                    │ NULL                                                                │ conceptual modeling: foundations and applications │ NULL                                                   │ NULL                 │ inproceedings │
│ Efficient Testing of Concurrent Programs with Abstraction-Guided Symbolic Execution.                                                      │ Neha Rungta|Eric G. Mercer|Willem Visser                                                                      │  2009 │  722399 │ conf/spin/RungtaMV09           │        4 │           0 │               0 │          1425 │              1425 │ NULL                                    │ NULL                                                                │ spin                                              │ NULL                                                   │ NULL                 │ phdthesis     │
│ Gasper Tkacik|William Bialek                                                                                                              │ Cell Biology: Networks, Regulation and Pathways.                                                              │  2009 │ 2425693 │ reference/complexity/TkacikB09 │        3 │           0 │               0 │          1430 │              1430 │ NULL                                    │ NULL                                                                │ encyclopedia of complexity and systems science    │ NULL                                                   │ NULL                 │ article       │
│ Neelakantan Sundaresan|Dennis Gannon                                                                                                      │ A Thread Model for Supporting Task and Data Parallelism in Object-Oriented Languages.                         │  1995 │  406516 │ conf/icpp/SundaresanG95        │        1 │           0 │               0 │          1433 │              1433 │ NULL                                    │ NULL                                                                │ icpp (2)                                          │ NULL                                                   │ NULL                 │ inproceedings │
│ Zeeshan Syed|John V. Guttag                                                                                                               │ Prototypical Biological Signals.                                                                              │  2007 │  900353 │ conf/icassp/SyedG07            │        1 │           0 │               0 │          1434 │              1434 │ NULL                                    │ NULL                                                                │ icassp (1)                                        │ NULL                                                   │ NULL                 │ inproceedings │
│ Design of PCI 2.2 Target Controller to Support Prefetch Request.                                                                          │ Eugin Hyun|Kyo-Yong Han|Kwang-Su Seong                                                                        │  2005 │   99433 │ conf/cdes/HyunHS05             │        1 │           0 │               0 │          1299 │              1299 │ NULL                                    │ NULL                                                                │ cdes                                              │ NULL                                                   │ NULL                 │ inproceedings │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┴─────────┴────────────────────────────────┴──────────┴─────────────┴─────────────────┴───────────────┴───────────────────┴─────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────┴────────────────────────────────────────────────────────┴──────────────────────┴───────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        16 columns

## PKey

## Swapping Author and Title
- Performing the swap when ptitle has a "|"

In [51]:
con.query("""
    UPDATE ducktable
    SET 
        ptitle  = pauthor,
        pauthor = ptitle
    WHERE ptitle LIKE '%|%'
""")

Now we take care of the rows that have swapped author and title when there is only one author (that the previous cell might have missed)

In [52]:
con.query("""
    UPDATE ducktable
    SET
        ptitle  = pauthor,
        pauthor = ptitle
    WHERE
        LENGTH(ptitle) < LENGTH(pauthor) AND 
        (LOWER(pauthor) LIKE '% of %' OR LOWER(pauthor) LIKE '% the %' 
        OR LOWER(pauthor) LIKE '% for %' OR LOWER(pauthor) LIKE '% on %'
        OR LOWER(pauthor) LIKE '% in %' OR LOWER(pauthor) LIKE '% with %' OR LOWER(pauthor) LIKE '% is %') 
    """)

con.query(""" SELECT ptitle, pauthor FROM ducktable""").show()

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                  ptitle                                                                   │                                                        pauthor                                                        │
│                                                                  varchar                                                                  │                                                        varchar                                                        │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Improving the Tolerance of Pipeline Based Circuits to Power Supply or Temperature Variations.                                             │ Jorge Semião|Juan J. Rodríguez-Andina|Fabian Vargas|Marcelino Bicho Dos Santos|Isabel C. Teixeira|João Paulo Teixeira │
│ A Normative Multi-Agent Systems Approach to the Use of Conviviality for Digital Cities.                                                   │ Patrice Caire                                                                                                         │
│ Self-Orthogonality of q-Ary Images of qm-Ary Codes and Quantum Code Construction.                                                         │ Sundeep B|Andrew Thangaraj                                                                                            │
│ OMG Data-Distribution Service: Architectural Overview.                                                                                    │ Gerardo Pardo-Castellote                                                                                              │
│ Structural Consistency: Enabling XML Keyword Search to Eliminate Spurious Results Consistently                                            │ Ki-Hoon Lee|Kyu-Young Whang|Wook-Shin Han|Min-Soo Kim 0002                                                            │
│ Input-to-state stability for a class of hybrid dynamical systems via hybrid time approach.                                                │ Bin Liu|David J. Hill|Kok Lay Teo                                                                                     │
│ A fourth-order compact difference scheme on face centered cubic grids with multigrid method for solving 2D convection diffusion equation. │ Haiwei Sun|Ning Kang|Jun Zhang|Eric S. Carlson                                                                        │
│ Performance Improvement of Intelligent UWB-IR Communication System in Multipath Channel.                                                  │ Sang-Heon Lee|Nam-Sung Kim|Heau-Jo Kang|Soon-Gohn Kim                                                                 │
│ IEEE 802.15.4 Performance on a Hierarchical Hybrid Sensor Network Platform.                                                               │ Eugene Pamba Capo-Chichi|Hervé Guyennet|Jean-Michel Friedt                                                            │
│ Scaffolding preservice teachers' WebQuest design: a qualitative study.                                                                    │ Feng Wang|Michael J. Hannafin                                                                                         │
│                                   ·                                                                                                       │             ·                                                                                                         │
│                                   ·                                                                                                       │             ·                                                                                                         │
│                                   ·                                                                                                       │             ·                                                                                                         │
│ Bilateral inversions and terminating basic hypergeometric series identities.                                                              │ Wenchang Chu|Chenying Wang                                                                                            │
│ Introductory Pre-College Engineering Design Course Based upon Collaborative Learning to High School Students.                             │ Masakatsu Matsuishi|Toru Kitamura                                                                                     │
│ Computational Properties of Probabilistic Neural Networks.                                                                                │ Jiri Grim|Jan Hora                                                                                                    │
│ LIV - The Linux Integrated Viruswall.                                                                                                     │ Teobaldo A. Dantas de Medeiros|Paulo S. Motta Pires                                                                   │
│ Data Modeling in Dataspace Support Platforms.                                                                                             │ Anish Das Sarma|Xin Luna Dong|Alon Y. Halevy                                                                          │
│ Efficient Testing of Concurrent Programs with Abstraction-Guided Symbolic Execution.                                                      │ Neha Rungta|Eric G. Mercer|Willem Visser                                                                              │
│ Cell Biology: Networks, Regulation and Pathways.                                                                                          │ Gasper Tkacik|William Bialek                                                                                          │
│ A Thread Model for Supporting Task and Data Parallelism in Object-Oriented Languages.                                                     │ Neelakantan Sundaresan|Dennis Gannon                                                                                  │
│ Prototypical Biological Signals.                                                                                                          │ Zeeshan Syed|John V. Guttag                                                                                           │
│ Design of PCI 2.2 Target Controller to Support Prefetch Request.                                                                          │ Eugin Hyun|Kyo-Yong Han|Kwang-Su Seong                                                                                │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                           2 columns

We can also perform the swap when authors end with a period - that should be a title

In [53]:
con.query("""
    UPDATE ducktable
    SET ptitle = pauthor, pauthor = ptitle
    WHERE pauthor LIKE '%.'
    AND ptitle NOT LIKE '%.'
""")

## Normalise Author and Title

In [54]:
con.query(r"""
    UPDATE ducktable
    SET 
        ptitle  = LOWER(TRIM(REGEXP_REPLACE(ptitle, '\s+', ' ', 'g'))),
        pauthor = LOWER(TRIM(REGEXP_REPLACE(pauthor, '\s+', ' ', 'g')))
""")

## Saving Clean Data

In [55]:
con.query("""SELECT * FROM ducktable""").show()

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┬─────────┬────────────────────────────────┬──────────┬─────────────┬─────────────────┬───────────────┬───────────────────┬─────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────┬────────────────────────────────────────────────────────┬──────────────────────┬───────────────┐
│                                                        pauthor                                                        │                                                                  ptitle                                                                   │ pyear │   pid   │              pkey              │ ptype_id │ pjournal_id │ pjournalfull_id │ pbooktitle_id │ pbooktitlefull_id │                 journal                 │                             journalfull                             │                     booktitle                     │                     booktitlefull                      │ journal_abbreviation │     ptype     │
│                                                        varchar                                                        │                                                                  varchar                                                                  │ int64 │  int64  │            varchar             │  int64   │    int64    │      int64      │     int64     │       int64       │                 varchar                 │                               varchar                               │                      varchar                      │                        varchar                         │       varchar        │    varchar    │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────┼─────────┼────────────────────────────────┼──────────┼─────────────┼─────────────────┼───────────────┼───────────────────┼─────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────┼────────────────────────────────────────────────────────┼──────────────────────┼───────────────┤
│ jorge semião|juan j. rodríguez-andina|fabian vargas|marcelino bicho dos santos|isabel c. teixeira|joão paulo teixeira │ improving the tolerance of pipeline based circuits to power supply or temperature variations.                                             │  2007 │  180843 │ conf/dft/SemiaoRVSTT07         │        1 │           0 │               0 │             4 │                 4 │ NULL                                    │ NULL                                                                │ dft                                               │ dft                                                    │ NULL                 │ inproceedings │
│ patrice caire                                                                                                         │ a normative multi-agent systems approach to the use of conviviality for digital cities.                                                   │  2007 │  162991 │ conf/dagstuhl/Caire07          │        1 │           0 │               0 │             7 │                 7 │ NULL                                    │ NULL                                                                │ normative multi agent systems                     │ european grid conference                               │ NULL                 │ inproceedings │
│ sundeep b|andrew thangaraj                                                                                            │ self-orthogonality of q-ary images of qm-ary codes and quantum code construction.                                                         │  2007 │ 2261406 │ journals/tit/BT07              │        3 │           2 │               2 │             9 │                 9 │ ieee transactions on information theory │ international journal of ambient computing and intelligence (ijaci) │ wimob                                             │ acm symposium on parallel algorithms and architectures │ ijaci                │ article       │
│ gerardo pardo-castellote                                                                                              │ omg data-distribution service: architectural overview.                                                                                    │  2003 │  349720 │ conf/icdcsw/Pardo-Castellote03 │        1 │           0 │               0 │            11 │                11 │ NULL                                    │ NULL                                                                │ icdcs workshops                                   │ international agent technology conference              │ monet                │ inproceedings │
│ ki-hoon lee|kyu-young whang|wook-shin han|min-soo kim 0002                                                            │ structural consistency: enabling xml keyword search to eliminate spurious results consistently                                            │  2009 │ 1922328 │ journals/corr/abs-0911-4329    │        3 │           5 │               5 │             5 │                 5 │ corr                                    │ international journal of wireless information networks              │ NULL                                              │ NULL                                                   │ NULL                 │ article       │
│ bin liu|david j. hill|kok lay teo                                                                                     │ input-to-state stability for a class of hybrid dynamical systems via hybrid time approach.                                                │  2009 │  883711 │ conf/cdc/LiuHT09               │        1 │           0 │               0 │             5 │                 5 │ NULL                                    │ NULL                                                                │ NULL                                              │ NULL                                                   │ NULL                 │ inproceedings │
│ haiwei sun|ning kang|jun zhang|eric s. carlson                                                                        │ a fourth-order compact difference scheme on face centered cubic grids with multigrid method for solving 2d convection diffusion equation. │  2003 │ 2324621 │ journals/mcs/SunKZC03          │        3 │           6 │               6 │             5 │                 5 │ mathematics and computers in simulation │ international transactions on systems science and applications      │ NULL                                              │ NULL                                                   │ NULL                 │ article       │
│ sang-heon lee|nam-sung kim|heau-jo kang|soon-gohn kim                                                                 │ performance improvement of intelligent uwb-ir communication system in multipath channel.                                                  │  2006 │  366780 │ conf/icic/LeeKKK06             │        3 │           0 │               0 │             0 │                 0 │ NULL                                    │ NULL                                                                │ NULL                                              │ NULL                                                   │ NULL                 │ article       │
│ eugene pamba capo-chichi|hervé guyennet|jean-michel friedt                                                            │ ieee 802.15.4 performance on a hierarchical hybrid sensor network platform.                                                               │  2009 │  794722 │ conf/icns/Capo-ChichiGF09      │        1 │           0 │               0 │            15 │                15 │ NULL                                    │ NULL                                                                │ icns                                              │ asia pacific web conference                            │ ijbra                │ inproceedings │
│ feng wang|michael j. hannafin                                                                                         │ scaffolding preservice teachers' webquest design: a qualitative study.                                                                    │  2009 │ 2339884 │ journals/jche/WangH09          │        3 │          10 │              10 │             5 │                 5 │ j. computing in higher education        │ journal of computers                                                │ NULL                                              │ NULL                                                   │ ijhpcn               │ article       │
│             ·                                                                                                         │                                   ·                                                                                                       │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │  ·                   │    ·          │
│             ·                                                                                                         │                                   ·                                                                                                       │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │  ·                   │    ·          │
│             ·                                                                                                         │                                   ·                                                                                                       │    ·  │    ·    │         ·                      │        · │           · │               · │             · │                 · │          ·                              │          ·                                                          │  ·                                                │  ·                                                     │  ·                   │    ·          │
│ wenchang chu|chenying wang                                                                                            │ bilateral inversions and terminating basic hypergeometric series identities.                                                              │  2009 │ 1957806 │ journals/dm/ChuW09             │        1 │          68 │              68 │          1396 │              1396 │ discrete mathematics                    │ journal of information & knowledge management                       │ csse (4)                                          │ NULL                                                   │ NULL                 │ inproceedings │
│ masakatsu matsuishi|toru kitamura                                                                                     │ introductory pre-college engineering design course based upon collaborative learning to high school students.                             │  2006 │  731619 │ conf/sutc/MatsuishiK06         │        3 │           0 │               0 │          1414 │              1414 │ NULL                                    │ NULL                                                                │ sutc (2)                                          │ NULL                                                   │ NULL                 │ article       │
│ jiri grim|jan hora                                                                                                    │ computational properties of probabilistic neural networks.                                                                                │  2010 │  320632 │ conf/icann/GrimH10             │        1 │           0 │               0 │          1416 │              1416 │ NULL                                    │ NULL                                                                │ icann (3)                                         │ NULL                                                   │ NULL                 │ inproceedings │
│ teobaldo a. dantas de medeiros|paulo s. motta pires                                                                   │ liv - the linux integrated viruswall.                                                                                                     │  2004 │  183968 │ conf/dimva/MedeirosP04         │        1 │           0 │               0 │          1419 │              1419 │ NULL                                    │ NULL                                                                │ dimva                                             │ NULL                                                   │ NULL                 │ inproceedings │
│ anish das sarma|xin luna dong|alon y. halevy                                                                          │ data modeling in dataspace support platforms.                                                                                             │  2009 │   78605 │ conf/birthday/SarmaDH09        │        1 │           0 │               0 │          1423 │              1423 │ NULL                                    │ NULL                                                                │ conceptual modeling: foundations and applications │ NULL                                                   │ NULL                 │ inproceedings │
│ neha rungta|eric g. mercer|willem visser                                                                              │ efficient testing of concurrent programs with abstraction-guided symbolic execution.                                                      │  2009 │  722399 │ conf/spin/RungtaMV09           │        4 │           0 │               0 │          1425 │              1425 │ NULL                                    │ NULL                                                                │ spin                                              │ NULL                                                   │ NULL                 │ phdthesis     │
│ gasper tkacik|william bialek                                                                                          │ cell biology: networks, regulation and pathways.                                                                                          │  2009 │ 2425693 │ reference/complexity/TkacikB09 │        3 │           0 │               0 │          1430 │              1430 │ NULL                                    │ NULL                                                                │ encyclopedia of complexity and systems science    │ NULL                                                   │ NULL                 │ article       │
│ neelakantan sundaresan|dennis gannon                                                                                  │ a thread model for supporting task and data parallelism in object-oriented languages.                                                     │  1995 │  406516 │ conf/icpp/SundaresanG95        │        1 │           0 │               0 │          1433 │              1433 │ NULL                                    │ NULL                                                                │ icpp (2)                                          │ NULL                                                   │ NULL                 │ inproceedings │
│ zeeshan syed|john v. guttag                                                                                           │ prototypical biological signals.                                                                                                          │  2007 │  900353 │ conf/icassp/SyedG07            │        1 │           0 │               0 │          1434 │              1434 │ NULL                                    │ NULL                                                                │ icassp (1)                                        │ NULL                                                   │ NULL                 │ inproceedings │
│ eugin hyun|kyo-yong han|kwang-su seong                                                                                │ design of pci 2.2 target controller to support prefetch request.                                                                          │  2005 │   99433 │ conf/cdes/HyunHS05             │        1 │           0 │               0 │          1299 │              1299 │ NULL                                    │ NULL                                                                │ cdes                                              │ NULL                                                   │ NULL                 │ inproceedings │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┴─────────┴────────────────────────────────┴──────────┴─────────────┴─────────────────┴───────────────┴───────────────────┴─────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────┴────────────────────────────────────────────────────────┴──────────────────────┴───────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                16 columns

In [56]:
final_pandas_df = con.query("""SELECT * FROM ducktable""").to_df()
final_pandas_df.drop(columns=['ptype_id', 'pjournal_id', 'pjournalfull_id', 'pbooktitle_id', 'pbooktitlefull_id'], inplace=True)
final_pandas_df.head()

,pauthor,ptitle,pyear,pid,pkey,journal,journalfull,booktitle,booktitlefull,journal_abbreviation,ptype
0,jorge semião|juan j. rodríguez-andina|fabian v...,improving the tolerance of pipeline based circ...,2007,180843,conf/dft/SemiaoRVSTT07,NaN,NaN,dft,dft,NaN,inproceedings
1,patrice caire,a normative multi-agent systems approach to th...,2007,162991,conf/dagstuhl/Caire07,NaN,NaN,normative multi agent systems,european grid conference,NaN,inproceedings
2,sundeep b|andrew thangaraj,self-orthogonality of q-ary images of qm-ary c...,2007,2261406,journals/tit/BT07,ieee transactions on information theory,international journal of ambient computing and...,wimob,acm symposium on parallel algorithms and archi...,ijaci,article
3,gerardo pardo-castellote,omg data-distribution service: architectural o...,2003,349720,conf/icdcsw/Pardo-Castellote03,NaN,NaN,icdcs workshops,international agent technology conference,monet,inproceedings
4,ki-hoon lee|kyu-young whang|wook-shin han|min-...,structural consistency: enabling xml keyword s...,2009,1922328,journals/corr/abs-0911-4329,corr,international journal of wireless information ...,NaN,NaN,NaN,article

In [57]:
final_pandas_df.to_csv(DATA_DIR / "duckdb_cleaned_dblp_v2.csv", index=False)